FROM node:18-alpine AS build

WORKDIR /app

COPY frontend/package.json frontend/package-lock.json ./

RUN npm install

COPY frontend/ . 


ENV NODE_OPTIONS="--openssl-legacy-provider"

RUN npm run build

RUN npm install -g serve
EXPOSE 3000 

CMD ["serve", "-s", "build", "-l", "3000"]
